name: Release

on:
  push:
    tags:
      - 'v*.*.*'

# 添加权限配置
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive-name: fishpi-client-windows-x64.zip
            
          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive-name: fishpi-client-linux-x64.tar.gz
            
          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            archive-name: fishpi-client-macos-x64.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build client
        run: cargo build --release --target ${{ matrix.target }} --bin client

      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -ItemType Directory -Path "release" -Force
          Copy-Item "target\${{ matrix.target }}\release\client.exe" "release\"
          Copy-Item "README.md" "release\"
          Compress-Archive -Path "release\*" -DestinationPath "${{ matrix.archive-name }}"

      - name: Package Unix
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/client release/
          cp README.md release/
          cd release
          tar -czf ../${{ matrix.archive-name }} *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive-name }}
          path: ${{ matrix.archive-name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: FishPi Client ${{ steps.version.outputs.VERSION }}
          body: |
            ## FishPi 聊天室客户端 ${{ steps.version.outputs.VERSION }}
            
            ### 下载
            - **Windows**: `fishpi-client-windows-x64.zip`
            - **Linux**: `fishpi-client-linux-x64.tar.gz`
            - **macOS**: `fishpi-client-macos-x64.tar.gz`
            
            ### 使用方法
            1. 下载对应平台的文件
            2. 解压缩
            3. 运行 `client` 程序
          files: artifacts/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
